# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe/speed_coe.xci
# IP: The module: 'speed_coe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe/speed_coe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'speed_coe'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe/speed_coe.xci
# IP: The module: 'speed_coe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe/speed_coe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'speed_coe'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
