#Clock
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

#VGA
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[0]}]

set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN J18 [get_ports {b_out[0]}]
set_property PACKAGE_PIN K18 [get_ports {b_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {b_out[2]}]
set_property PACKAGE_PIN N18 [get_ports {b_out[3]}]
set_property PACKAGE_PIN D17 [get_ports {g_out[0]}]
set_property PACKAGE_PIN G17 [get_ports {g_out[1]}]
set_property PACKAGE_PIN H17 [get_ports {g_out[2]}]
set_property PACKAGE_PIN J17 [get_ports {g_out[3]}]
set_property PACKAGE_PIN N19 [get_ports {r_out[0]}]
set_property PACKAGE_PIN J19 [get_ports {r_out[1]}]
set_property PACKAGE_PIN H19 [get_ports {r_out[2]}]
set_property PACKAGE_PIN G19 [get_ports {r_out[3]}]

#reset
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

#SPI
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports slaveselect]

set_property PACKAGE_PIN K17 [get_ports spi_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {spi_clk_IBUF}]
set_property PACKAGE_PIN P18 [get_ports miso]
set_property PACKAGE_PIN N17 [get_ports mosi]
set_property PACKAGE_PIN M18 [get_ports slaveselect]

#Led's
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

set_property PACKAGE_PIN L1 [get_ports {LED[7]}]
set_property PACKAGE_PIN P1 [get_ports {LED[6]}]
set_property PACKAGE_PIN N3 [get_ports {LED[5]}]
set_property PACKAGE_PIN P3 [get_ports {LED[4]}]
set_property PACKAGE_PIN U3 [get_ports {LED[3]}]
set_property PACKAGE_PIN W3 [get_ports {LED[2]}]
set_property PACKAGE_PIN V3 [get_ports {LED[1]}]
set_property PACKAGE_PIN V13 [get_ports {LED[0]}]
