# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Progh/Game/Game.srcs/sources_1/ip/clk_wiz
    c:/Progh/Game/Game.srcs/sources_1/ip/block_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/wall_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/player1_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/player2_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/heart_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/bomb_up_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/freeze_coe
    c:/Progh/Game/Game.srcs/sources_1/ip/bomb_coe
  } {
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/clk_wiz_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/block_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/wall_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/player1_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/player2_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/speed_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/heart_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/bomb_up_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/freeze_coe_stub.vhdl
      C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/bomb_coe_stub.vhdl
      C:/Progh/Game/Game.srcs/sources_1/new/color_scheme.vhd
      C:/Progh/Game/Game.srcs/sources_1/new/spi.vhd
      C:/Progh/Game/Game.srcs/sources_1/new/image1.vhd
      C:/Progh/Game/Game.srcs/sources_1/new/vga.vhd
      C:/Progh/Game/Game.srcs/sources_1/new/top.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Progh/Game/Game.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Progh/Game/Game.runs/synth_1/.Xil/Vivado-26064-LAPTOP-OQJ5SABP/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
