set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/clk_wiz/clk_wiz/clk_wiz_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/clk_wiz/clk_wiz/clk_wiz_in_context.xdc id:1 order:EARLY scoped_inst:clock_layout} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/block_coe/block_coe/block_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/block_coe/block_coe/block_coe_in_context.xdc id:2 order:EARLY scoped_inst:screen_writer_layout/block_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/wall_coe/wall_coe/wall_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/wall_coe/wall_coe/wall_coe_in_context.xdc id:3 order:EARLY scoped_inst:screen_writer_layout/wall_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/player1_coe/player1_coe/player1_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/player1_coe/player1_coe/player1_coe_in_context.xdc id:4 order:EARLY scoped_inst:screen_writer_layout/player1_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/player2_coe/player2_coe/player2_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/player2_coe/player2_coe/player2_coe_in_context.xdc id:5 order:EARLY scoped_inst:screen_writer_layout/player2_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/speed_coe/speed_coe/speed_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/speed_coe/speed_coe/speed_coe_in_context.xdc id:6 order:EARLY scoped_inst:screen_writer_layout/speed_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/heart_coe/heart_coe/heart_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/heart_coe/heart_coe/heart_coe_in_context.xdc id:7 order:EARLY scoped_inst:screen_writer_layout/heart_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/bomb_up_coe/bomb_up_coe/bomb_up_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/bomb_up_coe/bomb_up_coe/bomb_up_coe_in_context.xdc id:8 order:EARLY scoped_inst:screen_writer_layout/bomb_up_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/freeze_coe/freeze_coe/freeze_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/freeze_coe/freeze_coe/freeze_coe_in_context.xdc id:9 order:EARLY scoped_inst:screen_writer_layout/freeze_ram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Progh/Game/Game.srcs/sources_1/ip/bomb_coe/bomb_coe/bomb_coe_in_context.xdc rfile:../../../../../Game.srcs/sources_1/ip/bomb_coe/bomb_coe/bomb_coe_in_context.xdc id:10 order:EARLY scoped_inst:screen_writer_layout/bomb_ram} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Progh/Game/Game.srcs/constrs_1/new/constraint.xdc rfile:../../../../../Game.srcs/constrs_1/new/constraint.xdc id:11} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_layout/clk_out -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins clock_layout/clk_out]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_layout/clk_pixel -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 14.789 29.579} [get_pins clock_layout/clk_pixel]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clock_layout]
current_instance screen_writer_layout/block_ram
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/block_ram]
current_instance screen_writer_layout/wall_ram
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/wall_ram]
current_instance screen_writer_layout/player1_ram
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/player1_ram]
current_instance screen_writer_layout/player2_ram
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/player2_ram]
current_instance screen_writer_layout/speed_ram
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/speed_ram]
current_instance screen_writer_layout/heart_ram
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/heart_ram]
current_instance screen_writer_layout/bomb_up_ram
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/bomb_up_ram]
current_instance screen_writer_layout/freeze_ram
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/freeze_ram]
current_instance screen_writer_layout/bomb_ram
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen_writer_layout/bomb_ram]
set_property src_info {type:XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:11 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property src_info {type:XDC file:11 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property src_info {type:XDC file:11 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[3]}]
set_property src_info {type:XDC file:11 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[2]}]
set_property src_info {type:XDC file:11 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[1]}]
set_property src_info {type:XDC file:11 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out[0]}]
set_property src_info {type:XDC file:11 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[3]}]
set_property src_info {type:XDC file:11 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[2]}]
set_property src_info {type:XDC file:11 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[1]}]
set_property src_info {type:XDC file:11 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {g_out[0]}]
set_property src_info {type:XDC file:11 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[3]}]
set_property src_info {type:XDC file:11 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[2]}]
set_property src_info {type:XDC file:11 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[1]}]
set_property src_info {type:XDC file:11 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {r_out[0]}]
set_property src_info {type:XDC file:11 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property src_info {type:XDC file:11 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property src_info {type:XDC file:11 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property src_info {type:XDC file:11 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property src_info {type:XDC file:11 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports slaveselect]
set_property src_info {type:XDC file:11 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property src_info {type:XDC file:11 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property src_info {type:XDC file:11 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property src_info {type:XDC file:11 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property src_info {type:XDC file:11 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property src_info {type:XDC file:11 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property src_info {type:XDC file:11 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property src_info {type:XDC file:11 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property src_info {type:XDC file:11 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
set_property src_info {type:XDC file:11 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property src_info {type:XDC file:11 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property src_info {type:XDC file:11 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property src_info {type:XDC file:11 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property src_info {type:XDC file:11 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property src_info {type:XDC file:11 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property src_info {type:XDC file:11 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells clock_layout]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/block_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/wall_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/player1_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/player2_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/speed_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/heart_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/bomb_up_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/freeze_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells screen_writer_layout/bomb_ram]
